
DROP TABLE IF EXISTS GUIDES;

DROP TABLE IF EXISTS PLACES;

DROP TABLE IF EXISTS ACTIVITIES;

DROP TABLE IF EXISTS CATEGORIES;

DROP TABLE IF EXISTS COMMENTS;

DROP TABLE IF EXISTS USERS;

DROP TABLE IF EXISTS RESOURCES;
